name: Build iOS app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install cordova
      run: npm install -g cordova
    - name: Create project
      run: |
        cordova create planromero
        cp -rf config.xml index.html main.html planromero/
        cp -rf resources planromero/
        cp -rf css fonts img js lib planromero/www/
    - name: Generate xcode project
      run: |
          cd planromero
          cordova platform add ios
          cordova prepare ios
    - name: Upload xcode project
      uses: actions/upload-artifact@v1
      with:
        name: xcodeproject
        path: planromero/platforms/ios/              
#    - name: Upload IPA
#      uses: actions/upload-artifact@v1
#      with:
#        name: app
#        path: platforms/ios/build/emulator/Ionic\ Conference\ App.app
