name: Build iOS app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Generate xcode project
      run: npm install -g cordova
    - name: Generate xcode project
      run: |
          cordova platform add ios
          cordova prepare ios
    - name: Upload xcode project
      run: |
          cd platforms/ios
    - name: Upload xcode project
      uses: actions/upload-artifact@v1
      with:
        name: xcodeproject
        path: platforms/ios/              
#    - name: Upload IPA
#      uses: actions/upload-artifact@v1
#      with:
#        name: app
#        path: platforms/ios/build/emulator/Ionic\ Conference\ App.app
